name: build-api
on: 
  push: # runs on every push to this repo
  pull_request: # and for outside collaborations
  release:
   types:
    - released
jobs:
  defaults:
    run:
      working-directory: pilas-bloques-api
  test: # condition below avoids double runs for local pull requests:
    if: ${{ github.event_name == 'push' || !startsWith(github.event.pull_request.head.repo.full_name, github.repository_owner) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: supercharge/mongodb-github-action@1.6.0

      #https://docs.github.com/es/actions/guides/caching-dependencies-to-speed-up-workflows#using-the-cache-action
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm install

      - name: Run tests
        run: npm run test

  package-release:
    if: github.event_name == 'release'
    needs: test
    uses: Program-AR/pilas-bloques-backend/pilas-bloques-api/.github/workflows/release.yml@master
    with:
      asset_name: pilasbloques-api.tar.gz
      asset_path: ./pilasbloques-api.tar.gz
        
