#Mostly the same as https://github.com/Program-AR/pilas-bloques-api/blob/master/.github/workflows/build.yml
name: build-analytics
on: 
  push:
  release:
   types:
    - released
jobs:
  test:
    defaults:
      run:
        working-directory: pilas-bloques-analytics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: supercharge/mongodb-github-action@1.6.0

      #https://docs.github.com/es/actions/guides/caching-dependencies-to-speed-up-workflows#using-the-cache-action
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm install

      - name: Run tests
        run: npm run test

  package-release:
    if: github.event_name == 'release'
    needs: test
    uses: Program-AR/pilas-bloques-backend/.github/workflows/release-api.yml@main
    with:
      asset_name: pilasbloques-analytics.tar.gz
      asset_path: ./pilasbloques-analytics.tar.gz
        
